/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/SM_BigCloud.glb -o src/models/BigCloud.tsx --typescript -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane018: THREE.Mesh
    Plane011: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/SM_BigCloud.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} position={[25426.754, 82310.633, -378494.5]} rotation={[Math.PI / 2, 0, 0]} scale={[282083.906, 282084, 282084]} />
      <mesh geometry={nodes.Plane011.geometry} material={nodes.Plane011.material} position={[-248.545, 6626.854, -281480.094]} rotation={[Math.PI / 2, 0, 0]} scale={[165950.156, 165950.188, 165950.188]} />
    </group>
  )
}

useGLTF.preload('/models/SM_BigCloud.glb')
