/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/su7.glb -o src/models/CarMi.tsx --typescript -r public 
*/

import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { DissolveMaterial } from "@/experiences/Car/DissolveMaterial";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_32: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_35: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_41: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_45: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_47: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_52: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_24: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_28: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_56: THREE.Mesh;
    平面: THREE.Mesh;
    topLigt: THREE.Mesh;
  };
  materials: {
    ["interior1.001"]: THREE.MeshStandardMaterial;
    ["interior2.001"]: THREE.MeshStandardMaterial;
    ["M_BODY_inside.004"]: THREE.MeshStandardMaterial;
    Car_body: THREE.MeshPhysicalMaterial;
    ["M_BODY_black.004"]: THREE.MeshStandardMaterial;
    ["M_IRON.004"]: THREE.MeshStandardMaterial;
    ["interior3.001"]: THREE.MeshStandardMaterial;
    Car_window: THREE.MeshPhysicalMaterial;
    ["interior4.001"]: THREE.MeshStandardMaterial;
    ["M_ChePai.004"]: THREE.MeshStandardMaterial;
    ["M_LOGO.004"]: THREE.MeshStandardMaterial;
    Car_backlight: THREE.MeshStandardMaterial;
    Car_lightglass: THREE.MeshStandardMaterial;
    Car_frontlight: THREE.MeshStandardMaterial;
    Car_radar: THREE.MeshStandardMaterial;
    ["pasted__M_BODY_inside.001"]: THREE.MeshStandardMaterial;
    ["M_Wheel_ALL.002"]: THREE.MeshStandardMaterial;
    floor: THREE.MeshPhysicalMaterial;
  };
};

export function CarMi(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/su7.glb") as GLTFResult;

  const [texture] = useTexture(["/textures/full_body2.jpg"]);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.topLigt.geometry}
        material={nodes.topLigt.material}
        position={[-0.007, 11.686, -0.007]}
        scale={[27.643, 0.353, 17.251]}
      />
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={2.342}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_31.geometry}
              material={materials["M_BODY_inside.004"]}
            />
            <mesh
              geometry={nodes.Object_32.geometry}
              /*  material={materials.Car_body} */
            >
              <DissolveMaterial
                baseMaterial={materials.Car_body}
                color={""}
                visible={true}
                texture={texture}
              ></DissolveMaterial>
            </mesh>
            <mesh
              geometry={nodes.Object_33.geometry}
              material={materials["M_BODY_black.004"]}
            />
            <mesh
              geometry={nodes.Object_34.geometry}
              material={materials["M_IRON.004"]}
            />
            <mesh
              geometry={nodes.Object_35.geometry}
              material={materials["interior3.001"]}
            />
            <mesh
              geometry={nodes.Object_36.geometry}
              material={materials.Car_window}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_38.geometry}
              material={materials["M_BODY_inside.004"]}
            />
            <mesh
              geometry={nodes.Object_39.geometry}
              /* material={materials.Car_body} */
            >
              <DissolveMaterial
                baseMaterial={materials.Car_body}
                color={""}
                visible={true}
                texture={texture}
              ></DissolveMaterial>
            </mesh>
            <mesh
              geometry={nodes.Object_40.geometry}
              material={materials.Car_window}
            />
            <mesh
              geometry={nodes.Object_41.geometry}
              material={materials["interior3.001"]}
            />
            <mesh
              geometry={nodes.Object_42.geometry}
              material={materials["M_BODY_black.004"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_44.geometry}
              material={materials["M_BODY_inside.004"]}
            />
            <mesh geometry={nodes.Object_45.geometry}>
              <DissolveMaterial
                baseMaterial={materials.Car_body}
                color={""}
                visible={true}
                texture={texture}
              ></DissolveMaterial>
            </mesh>
            <mesh
              geometry={nodes.Object_46.geometry}
              material={materials["M_BODY_black.004"]}
            />
            <mesh
              geometry={nodes.Object_47.geometry}
              material={materials["M_IRON.004"]}
            />
            <mesh
              geometry={nodes.Object_48.geometry}
              material={materials["interior3.001"]}
            />
            <mesh
              geometry={nodes.Object_49.geometry}
              material={materials.Car_window}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_51.geometry}
              material={materials["M_BODY_inside.004"]}
            />
            <mesh
              geometry={nodes.Object_52.geometry}
              /*  material={materials.Car_body} */
            >
              <DissolveMaterial
                baseMaterial={materials.Car_body}
                color={""}
                visible={true}
                texture={texture}
              ></DissolveMaterial>
            </mesh>
            <mesh
              geometry={nodes.Object_53.geometry}
              material={materials.Car_window}
            />
            <mesh
              geometry={nodes.Object_54.geometry}
              material={materials["interior3.001"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_12.geometry}
              material={materials["M_IRON.004"]}
            />
            <mesh
              geometry={nodes.Object_13.geometry}
              material={materials["M_ChePai.004"]}
            />
            <mesh
              geometry={nodes.Object_14.geometry}
              material={materials["M_LOGO.004"]}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_18.geometry}
              /*  material={materials.Car_body} */
            >
              <DissolveMaterial
                baseMaterial={materials.Car_body}
                color={""}
                visible={true}
                texture={texture}
              ></DissolveMaterial>
            </mesh>
            <mesh
              geometry={nodes.Object_19.geometry}
              material={materials["M_BODY_inside.004"]}
            ></mesh>
            <mesh
              geometry={nodes.Object_20.geometry}
              material={materials["M_BODY_black.004"]}
            />
            <mesh
              geometry={nodes.Object_21.geometry}
              material={materials.Car_window}
            />
            <mesh
              geometry={nodes.Object_22.geometry}
              material={materials.Car_backlight}
            />
            <mesh
              geometry={nodes.Object_23.geometry}
              material={materials.Car_lightglass}
            />
            <mesh
              geometry={nodes.Object_24.geometry}
              material={materials.Car_frontlight}
            />
            <mesh
              geometry={nodes.Object_25.geometry}
              material={materials.Car_radar}
            />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <mesh
              geometry={nodes.Object_27.geometry}
              material={materials["M_BODY_black.004"]}
            />
            <mesh
              geometry={nodes.Object_28.geometry}
              material={materials["pasted__M_BODY_inside.001"]}
            />
            <mesh
              geometry={nodes.Object_29.geometry}
              material={materials["M_BODY_inside.004"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials["interior1.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials["interior2.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials["interior2.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials["interior4.001"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials["M_BODY_inside.004"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials["M_Wheel_ALL.002"]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.平面.geometry}
        material={materials.floor}
        scale={17.686}
      />
    </group>
  );
}

useGLTF.preload("/models/su7.glb");
