/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/coffee.glb -o src/models/Coffee.tsx --typescript -r public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    baked: THREE.Mesh;
  };
  materials: {
    baked: THREE.MeshBasicMaterial;
  };
};

export function Coffee(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/coffee.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.baked.geometry}
        material={materials.baked}
        position={[0, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/coffee.glb");
