/* eslint-disable @typescript-eslint/no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/Fish.gltf -o src/models/Fish.tsx --typescript -r public 
*/

import * as THREE from "three";
import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF, SkeletonUtils } from "three-stdlib";

type ActionName =
  | "Death"
  | "Duck"
  | "HitReact"
  | "Idle"
  | "Jump"
  | "Jump_Idle"
  | "Jump_Land"
  | "No"
  | "Punch"
  | "Run"
  | "Walk"
  | "Wave"
  | "Weapon"
  | "Yes";

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Sphere026: THREE.SkinnedMesh;
    Sphere026_1: THREE.SkinnedMesh;
    Sphere026_2: THREE.SkinnedMesh;
    Sphere026_3: THREE.SkinnedMesh;
    Sphere026_4: THREE.SkinnedMesh;
    Sphere026_5: THREE.SkinnedMesh;
    Root: THREE.Bone;
  };
  materials: {
    Fish_Main: THREE.MeshStandardMaterial;
    Fish_Secondary: THREE.MeshStandardMaterial;
    Eye_Black: THREE.MeshStandardMaterial;
    Eye_White: THREE.MeshStandardMaterial;
    Mouth: THREE.MeshStandardMaterial;
    Fish_Flaps: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

interface ExtraProps {
  hovered: boolean;
}

export function Fish({
  hovered,
  ...props
}: JSX.IntrinsicElements["group"] & ExtraProps) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, materials, animations } = useGLTF("/models/Fish.gltf");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(clone) as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const anim: ActionName = hovered ? "Wave" : "Idle";
    actions[anim]?.reset().fadeIn(0.5).play();
    return () => {
      actions[anim]?.fadeOut(0.5);
    };
  }, [hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Fish">
            <skinnedMesh
              name="Sphere026"
              geometry={nodes.Sphere026.geometry}
              material={materials.Fish_Main}
              skeleton={nodes.Sphere026.skeleton}
            />
            <skinnedMesh
              name="Sphere026_1"
              geometry={nodes.Sphere026_1.geometry}
              material={materials.Fish_Secondary}
              skeleton={nodes.Sphere026_1.skeleton}
            />
            <skinnedMesh
              name="Sphere026_2"
              geometry={nodes.Sphere026_2.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Sphere026_2.skeleton}
            />
            <skinnedMesh
              name="Sphere026_3"
              geometry={nodes.Sphere026_3.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Sphere026_3.skeleton}
            />
            <skinnedMesh
              name="Sphere026_4"
              geometry={nodes.Sphere026_4.geometry}
              material={materials.Mouth}
              skeleton={nodes.Sphere026_4.skeleton}
            />
            <skinnedMesh
              name="Sphere026_5"
              geometry={nodes.Sphere026_5.geometry}
              material={materials.Fish_Flaps}
              skeleton={nodes.Sphere026_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Fish.gltf");
