/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/models.glb -o src/models/Morph.tsx --typescript -r public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Torus001: THREE.Mesh;
    Suzanne: THREE.Mesh;
    Icosphere: THREE.Mesh;
    Text002: THREE.Mesh;
  };
  materials: {};
};

export function Morph(props: JSX.IntrinsicElements["group"]) {
  const { nodes } = useGLTF("/models/models.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
      />
      <mesh
        geometry={nodes.Suzanne.geometry}
        material={nodes.Suzanne.material}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={nodes.Icosphere.material}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={nodes.Text002.material}
      />
    </group>
  );
}

useGLTF.preload("/models/models.glb");
