/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/SM_Light.glb -o src/models/PolarLights.tsx --typescript -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane009: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/SM_Light.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane009.geometry} material={nodes.Plane009.material} rotation={[Math.PI / 2, 0.848, 0]} />
    </group>
  )
}

useGLTF.preload('/models/SM_Light.glb')
