/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/SM_Road.glb -o src/models/Road.tsx --typescript -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SM_MERGED517: THREE.Mesh
    SM_MERGED517_1: THREE.Mesh
    SM_MERGED518: THREE.Mesh
    SM_MERGED518_1: THREE.Mesh
    SM_MERGED519: THREE.Mesh
    SM_MERGED519_1: THREE.Mesh
    SM_MERGED520: THREE.Mesh
    SM_MERGED520_1: THREE.Mesh
    SM_MERGED521: THREE.Mesh
    SM_MERGED521_1: THREE.Mesh
    SM_MERGED522: THREE.Mesh
    SM_MERGED522_1: THREE.Mesh
    SM_MERGED523: THREE.Mesh
    SM_MERGED523_1: THREE.Mesh
    SM_MERGED524: THREE.Mesh
    SM_MERGED524_1: THREE.Mesh
    SM_MERGED525: THREE.Mesh
    SM_MERGED525_1: THREE.Mesh
    SM_MERGED526: THREE.Mesh
    SM_MERGED526_1: THREE.Mesh
    SM_MERGED527: THREE.Mesh
    SM_MERGED527_1: THREE.Mesh
    SM_MERGED528: THREE.Mesh
    SM_MERGED528_1: THREE.Mesh
  }
  materials: {
    M_0_Inst: THREE.MeshStandardMaterial
    M_0_Inst1: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/SM_Road.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-152.504, 0, 188.808]}>
        <mesh geometry={nodes.SM_MERGED517.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED517_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[183.436, 0, 2072.184]}>
        <mesh geometry={nodes.SM_MERGED518.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED518_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-70.568, 0, 1912.992]}>
        <mesh geometry={nodes.SM_MERGED519.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED519_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-138.458, 0, 1607.485]}>
        <mesh geometry={nodes.SM_MERGED520.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED520_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[134.274, 0, 1779.552]}>
        <mesh geometry={nodes.SM_MERGED521.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED521_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-129.094, 0, 1244.622]}>
        <mesh geometry={nodes.SM_MERGED522.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED522_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[133.103, 0, 1437.759]}>
        <mesh geometry={nodes.SM_MERGED523.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED523_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-235.612, 0, 845.473]}>
        <mesh geometry={nodes.SM_MERGED524.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED524_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[206.847, 0, 1032.757]}>
        <mesh geometry={nodes.SM_MERGED525.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED525_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-142.601, 0, 660.646]}>
        <mesh geometry={nodes.SM_MERGED526.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED526_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[82.905, 0, 400.516]}>
        <mesh geometry={nodes.SM_MERGED527.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED527_1.geometry} material={materials.M_0_Inst1} />
      </group>
      <group position={[-71.739, 0, 2244.25]}>
        <mesh geometry={nodes.SM_MERGED528.geometry} material={materials.M_0_Inst} />
        <mesh geometry={nodes.SM_MERGED528_1.geometry} material={materials.M_0_Inst1} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/SM_Road.glb')
