/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/sm_car-v1-v1.glb -o src/models/Temp.tsx --typescript -r public 
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Wheel001: THREE.Mesh;
    Wheel002: THREE.Mesh;
    body: THREE.Mesh;
    Object_37009: THREE.Mesh;
    Object_37009_1: THREE.Mesh;
    body_smoothblack: THREE.Mesh;
    ChePai: THREE.Mesh;
    dingbuleida: THREE.Mesh;
    DiPan: THREE.Mesh;
    DiPan001: THREE.Mesh;
    Glass: THREE.Mesh;
    Object_31006: THREE.Mesh;
    Object_31006_1: THREE.Mesh;
    interior: THREE.Mesh;
    interior001: THREE.Mesh;
    interior002: THREE.Mesh;
    interior003: THREE.Mesh;
    interior004: THREE.Mesh;
    interior006: THREE.Mesh;
    interior009: THREE.Mesh;
    interior011: THREE.Mesh;
    Object_14003: THREE.Mesh;
    Object_14003_1: THREE.Mesh;
    Light002: THREE.Mesh;
    Light003: THREE.Mesh;
    LightGlass: THREE.Mesh;
    Object_13006: THREE.Mesh;
    Object_13006_1: THREE.Mesh;
    Logo: THREE.Mesh;
    Logo001: THREE.Mesh;
    ShaChe: THREE.Mesh;
    YuGua: THREE.Mesh;
  };
  materials: {
    M_wheel: THREE.MeshStandardMaterial;
    Car_body: THREE.MeshStandardMaterial;
    M_body_smoothblack: THREE.MeshStandardMaterial;
    ["M_ChePai.004"]: THREE.MeshStandardMaterial;
    M_body_frostedblack: THREE.MeshStandardMaterial;
    Car_window: THREE.MeshStandardMaterial;
    Car_ight: THREE.MeshStandardMaterial;
    M_iron: THREE.MeshStandardMaterial;
    M_logo: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/sm_car-v1-v1.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.body.geometry}
        material={materials.Car_body}
        position={[-2.442, 0.888, 0]}
        scale={0.645}
      />
      <group position={[0.01, 0.842, 0]} scale={2.612}>
        <mesh
          geometry={nodes.Object_37009.geometry}
          material={materials.Car_body}
        />
        <mesh
          geometry={nodes.Object_37009_1.geometry}
          material={materials.M_body_smoothblack}
        />
      </group>
      <mesh
        geometry={nodes.body_smoothblack.geometry}
        material={materials.M_body_smoothblack}
        position={[0.012, 0.827, 0]}
        scale={2.618}
      />
      <mesh
        geometry={nodes.ChePai.geometry}
        material={materials["M_ChePai.004"]}
        position={[0.022, 0.524, 0]}
        scale={2.605}
      />
      <mesh
        geometry={nodes.dingbuleida.geometry}
        material={materials.M_body_smoothblack}
        position={[0.721, 1.185, 0]}
        scale={0.844}
      />
      <mesh
        geometry={nodes.DiPan.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.005, 0.771, 0]}
        scale={2.582}
      />
      <mesh
        geometry={nodes.DiPan001.geometry}
        material={materials.M_body_smoothblack}
        position={[-0.316, 1.187, 0]}
        scale={1.201}
      />
      <mesh
        geometry={nodes.Glass.geometry}
        material={materials.Car_window}
        position={[-0.438, 1.166, 0]}
        scale={1.652}
      />
      <group position={[0.708, 0.994, 0]} scale={1.1}>
        <mesh
          geometry={nodes.Object_31006.geometry}
          material={materials.Car_body}
        />
        <mesh
          geometry={nodes.Object_31006_1.geometry}
          material={materials.M_body_smoothblack}
        />
      </group>
      <mesh
        geometry={nodes.interior.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.105, 0.698, 0]}
        scale={1.026}
      />
      <mesh
        geometry={nodes.interior001.geometry}
        material={materials.M_body_frostedblack}
        position={[0.388, 0.702, 0.029]}
        scale={0.85}
      />
      <mesh
        geometry={nodes.interior002.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.573, 0.718, 0]}
        scale={0.847}
      />
      <mesh
        geometry={nodes.interior003.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.426, 0.812, 0]}
        scale={0.904}
      />
      <mesh
        geometry={nodes.interior004.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.614, 0.629, 0]}
        scale={1.731}
      />
      <mesh
        geometry={nodes.interior006.geometry}
        material={materials.M_body_frostedblack}
        position={[-0.491, 0.815, 0]}
        scale={1.476}
      />
      <mesh
        geometry={nodes.interior009.geometry}
        material={materials.M_body_frostedblack}
        position={[0.607, 0.869, -0.153]}
        scale={0.504}
      />
      <mesh
        geometry={nodes.interior011.geometry}
        material={materials.M_body_frostedblack}
        position={[0.406, 0.695, 0]}
        scale={0.938}
      />
      <group position={[2.26, 0.708, 0]} scale={0.872}>
        <mesh
          geometry={nodes.Object_14003.geometry}
          material={materials.Car_ight}
        />
        <mesh
          geometry={nodes.Object_14003_1.geometry}
          material={materials.M_iron}
        />
      </group>
      <mesh
        geometry={nodes.Light002.geometry}
        material={materials.M_body_smoothblack}
        position={[2.227, 0.705, 0]}
        scale={0.887}
      />
      <mesh
        geometry={nodes.Light003.geometry}
        material={materials.Car_ight}
        position={[-2.343, 0.68, 0]}
        scale={0.827}
      />
      <mesh
        geometry={nodes.LightGlass.geometry}
        material={materials.Car_window}
        position={[-2.281, 0.909, 0]}
        scale={0.867}
      />
      <group position={[2.263, 0.709, 0]} scale={0.882}>
        <mesh
          geometry={nodes.Object_13006.geometry}
          material={materials.Car_window}
        />
        <mesh
          geometry={nodes.Object_13006_1.geometry}
          material={materials.Car_ight}
        />
      </group>
      <mesh
        geometry={nodes.Logo.geometry}
        material={materials.M_iron}
        position={[-2.487, 0.857, 0.007]}
        scale={0.489}
      />
      <mesh
        geometry={nodes.Logo001.geometry}
        material={materials.M_logo}
        position={[2.372, 0.764, 0]}
        scale={0.034}
      />
      <mesh
        geometry={nodes.ShaChe.geometry}
        material={materials.M_wheel}
        position={[0.042, 0.371, 0]}
        rotation={[0, 0, -0.172]}
        scale={1.703}
      />
      <mesh
        geometry={nodes.YuGua.geometry}
        material={materials.M_body_frostedblack}
        position={[1.178, 0.974, 0.024]}
        scale={0.714}
      />
      <mesh
        geometry={nodes.Wheel001.geometry}
        material={materials.M_wheel}
        position={[1.569, 0.364, 0]}
        scale={0.98}
      />
      <mesh
        geometry={nodes.Wheel002.geometry}
        material={materials.M_wheel}
        position={[-1.484, 0.364, 0]}
        scale={0.966}
      />
    </group>
  );
}

useGLTF.preload("/models/sm_car-v1-v1.glb");
