/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 public/models/sm_speedup-v1.glb -o src/models/Tunnel.tsx --typescript -r public 
*/

import * as THREE from "three";
import React, { forwardRef, useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { GroupProps, useFrame } from "@react-three/fiber";
import { Group, Object4DEventMap } from "three";
import { CustomTunnelMaterial } from "@/experiences/Car/MiCarExperience";
import gsap from "gsap";

type GLTFResult = GLTF & {
  nodes: {
    加速002: THREE.Mesh;
  };
  materials: {};
};

export const Tunnel = forwardRef<
  Group<Object4DEventMap>,
  JSX.IntrinsicElements["group"]
>((props, ref) => {
  const { nodes, materials } = useGLTF(
    "/models/sm_speedup-v1.glb"
  ) as GLTFResult;

  const tunnelRef = useRef<THREE.Mesh>(null);
  const t4 = useRef(gsap.timeline());

  useFrame((state) => {
    CustomTunnelMaterial.uniforms.time.value = state.clock.getElapsedTime();
  });

  useEffect(() => {
    CustomTunnelMaterial.opacity = 0;
    tunnelRef.current!.layers.enable(1);
  }, []);

  useEffect(() => {
    window.addEventListener("mousedown", handleMouseDown);
    window.addEventListener("mouseup", handleMouseUp);
    window.addEventListener("touchstart", handleMouseDown);
    window.addEventListener("touchend", handleMouseUp);
    return () => {
      window.removeEventListener("mousedown", handleMouseDown);
      window.removeEventListener("mouseup", handleMouseUp);
      window.removeEventListener("touchstart", handleMouseDown);
      window.removeEventListener("touchend", handleMouseUp);
    };
  }, []);

  const handleMouseDown = (e: Event) => {
    //start transition

    //t4.current = gsap.timeline();
    t4.current.clear();
    t4.current.to(CustomTunnelMaterial.uniforms.opacity, {
      duration: 0.5,
      value: 1,
    });
  };
  const handleMouseUp = (e: Event) => {
    t4.current.clear();
    //revert animation
    t4.current.to(CustomTunnelMaterial.uniforms.opacity, {
      duration: 1,
      value: 0,
    });
  };

  return (
    <group {...props} dispose={null} /* position={[0, 0, 0]} */>
      <mesh
        geometry={nodes.加速002.geometry}
        material={CustomTunnelMaterial}
        position={[100, 3.335, 0]}
        scale={[215.94, 255.94, 215.94]}
        ref={tunnelRef}
      />
    </group>
  );
});

Tunnel.displayName = "Tunnel";

useGLTF.preload("/models/sm_speedup-v1.glb");
